# -*- coding: utf-8 -*-
"""Image to text (easyocr).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cSryUNewSI9x895Uy_SXc0XHrsYQI4dZ
"""

!pip install easyocr

import cv2
import numpy as np
import re

import torch
import easyocr

from google.colab import drive

# Accessing My Google Drive
drive.mount('/content/drive')

deteksi = easyocr.Reader(['id'], gpu=False)
foto = '/content/drive/MyDrive/Capstone/namecard1.jpg' ##minta storage ke andi: link
kata = deteksi.readtext(foto)

for a in kata:
  print(a)